#!/bin/sh

SCRIPT="$(basename $0)"

usage() {
cat <<EOH
Changes the AdGuard Home password and/or username.

Usage: $SCRIPT [parameters]

Parameters:
 -p password  The new plain text AdGuard Home web password (at least 8
                characters). The password will be hashed on this device by the
                installed AdGuard Home.
                This option is ignored if -h is specified.
 -h 'hash'    The Bcrypt password hash representing new the AdGuard Home web
                password.
                The hash value MUST be specified within single quotes.
                You can generate the hash on a computer with Apache htpasswd:
                  htpasswd -nbBC 10 "" 'password' | tr -d ':\n'
 -n username  The new AdGuard Home web user name.
 -U           Download the latest version of $SCRIPT from GitHub

EOH
exit
}

upgrade() {
  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/supplemental/adguard/$SCRIPT)
  if [ "$RESPONSE_CODE" = 200 ]
  then
    curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/supplemental/adguard/$SCRIPT
    if [ $? -eq 0 ]
    then
      chmod +x $SCRIPT
      echo "[$SCRIPT] Successfully downloaded $SCRIPT."
    else
      echo "[$SCRIPT] Failed to download $SCRIPT."
    fi
  elif [ "$RESPONSE_CODE" = 404 ]
  then
    echo "[$SCRIPT] ERROR! Not found on GitHub???"
  elif [ "$RESPONSE_CODE" = 000 ]
  then
    echo "[$SCRIPT] ERROR! No Internet connection???"
  else
    echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
  fi
  exit
}

# Sets PWD_HASH to the bcrypt hash of PASSWORD, generated on this device by AdGuard Home ($1) itself: a temporary
# instance listening only on loopback is set up through its first-run API, and the hash is read from the
# configuration file it writes. The password is not sent off the device.
agh_hash_password() {
  local dir=/tmp/agh-hash.$$ web_port=38008 dns_port=38053 pid code n=0
  rm -rf $dir
  mkdir -m 700 $dir || return 1
  $1 --no-check-update -c $dir/AdGuardHome.yaml -w $dir -h 127.0.0.1 -p $web_port > $dir/log 2>&1 &
  pid=$!
  while [ $n -lt 60 ] && kill -0 $pid 2>/dev/null; do
    curl -s -o /dev/null http://127.0.0.1:$web_port/control/install/get_addresses && break
    sleep 1
    n=$((n+1))
  done
  ( umask 077
    . /usr/share/libubox/jshn.sh
    json_init
    json_add_object web; json_add_string ip 127.0.0.1; json_add_int port $web_port; json_close_object
    json_add_object dns; json_add_string ip 127.0.0.1; json_add_int port $dns_port; json_close_object
    json_add_string username "${USERNAME:-root}"
    json_add_string password "$PASSWORD"
    json_dump > $dir/request.json )
  code=$(curl -s -o $dir/response -w '%{http_code}' -H 'Content-Type: application/json' --data-binary @$dir/request.json http://127.0.0.1:$web_port/control/install/configure)
  rm -f $dir/request.json
  [ "$code" = 200 ] && PWD_HASH=$(grep -o -m 1 '\$2[aby]\$[0-9][0-9]\$[./0-9A-Za-z]\{53\}' $dir/AdGuardHome.yaml)
  kill $pid 2>/dev/null
  wait $pid 2>/dev/null
  if [ -z "$PWD_HASH" ]; then
    echo -e "${RED}[$SCRIPT] Password hash failed with message: ${NC}$(cat $dir/response 2>/dev/null || tail -n 1 $dir/log)"
    rm -rf $dir
    return 1
  fi
  rm -rf $dir
}

GREEN='\033[1;32m'
ORANGE='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

USERNAME=''
PASSWORD=''
PWD_HASH=''

while getopts :h:n:p:U option
do
 case "${option}" in
  h)  PWD_HASH="$OPTARG";;
  n)  USERNAME="$OPTARG";;
  p)  PASSWORD="$OPTARG";;
  U)  upgrade;;
  *)  usage;;
 esac
done
shift $((OPTIND-1))

if [ -z "$PWD_HASH" -a -z "$PASSWORD" -a -z "$USERNAME" ]; then
  echo -e "${RED}[$SCRIPT] ERROR: No options specified?${NC}"
  usage
  exit 2
fi

AGH_YAML=$(grep -o -m 1 -E '"-c" "/.*/AdGuardHome/AdGuardHome.yaml"' /etc/init.d/AdGuardHome | cut -d'"' -f4)
if [ $? -ne 0 ]; then
  echo -e "${RED}[$SCRIPT] ERROR: Unable to locate AdGuard Home configuration file!${NC}"
  exit 2
fi

echo -e "${GREEN}[$SCRIPT] AdGuard Home configuration file = $AGH_YAML${NC}"
if [ -z "$PWD_HASH" -a -n "$PASSWORD" ]; then
  if [ ${#PASSWORD} -lt 8 ]; then
    echo -e "${RED}[$SCRIPT] The password must be at least 8 characters long! Aborting...${NC}"
    exit 2
  fi
  echo -e "${GREEN}[$SCRIPT] Generating password hash...${NC}"
  if ! agh_hash_password $(dirname $AGH_YAML)/AdGuardHome; then
    echo -e "${RED}[$SCRIPT] Aborting...${NC}"
    exit 2
  fi
fi

echo -e "${GREEN}[$SCRIPT] Stopping AdGuard Home temporarily${NC}"
/etc/init.d/AdGuardHome stop

echo -e "${GREEN}[$SCRIPT] Updating configuration${NC}"
sed -e "s|\( password: *\)\(.*\)|\1 $PWD_HASH|" -i $AGH_YAML
if [ -n "$USERNAME" ]; then
  sed -e "s|\(- name: *\)\(.*\)|\1 $USERNAME|" -i $AGH_YAML
fi

echo -e "${GREEN}[$SCRIPT] Re-starting AdGuard Home${NC}"
/etc/init.d/AdGuardHome start
