#!/bin/sh

VERSION="$(uci get version.@version[0].version | cut -d- -f1)"
SCRIPT="tch-gui-unhide-$VERSION"
DOWNLOAD=n
HELP=n

while getopts t:ryuUx:i: option
do
 case "${option}" in
   t|r|y|u|x|i) HELP=n;;
   U) DOWNLOAD=y;;
   *) HELP=y;;
 esac
done

if [ -f "$SCRIPT" -a "$DOWNLOAD" = "n" ]; then
  ./$SCRIPT -W $*
else
  if [ ! -f "$SCRIPT" ]; then
    echo "[tch-gui-unhide] Platform script $SCRIPT not found!"
  fi
  echo "[tch-gui-unhide] Attempting to download latest release for FW $VERSION from GitHub..."
  curl -k -L https://github.com/seud0nym/tch-gui-unhide/releases/latest/download/$VERSION.tar.gz | tar -xzvf -
fi 
