#!/bin/sh

BATCH=""
QUIET="n"
VERBOSE="n"
HIDE_EXTRA="1"
OPTS=0
while getopts sdqvaM option
do
  OPTS=$(( $OPTS + 1 ))
  case "${option}" in
    a)     HIDE_EXTRA="0";;
    s|d|M) BATCH="${option}";;
    q)     QUIET="y";;
    v)     VERBOSE="y";;
    *)     OPTS=$(( $OPTS - 1 ));;
  esac
done

if [ $# -ne $OPTS ]
then
  echo
  echo "Optional parameters:"
  echo " -s       : Apply the suggested card sequence and exit"
  echo " -d       : Apply the default card sequence and exit"
  echo
  echo "If BOTH parameters are specified, only the LAST will be applied."
  echo
  echo "When NO parameters are specified, you can interactively re-sequence cards and change their visibility."
  echo
  exit
fi

[ $QUIET = n ] && echo -n "Working"
CARDS=""
for RULE in $(uci show web | grep '=card' | cut -d= -f1)
do
  [ $QUIET = n ] && echo -n "."
  CARD=$(uci -q get ${RULE}.card)
  MODAL=$(uci -q get ${RULE}.modal)
  HIDDEN=$(uci -q get ${RULE}.hide)
  if [ "${CARD#*_}" = "lte.lp" ]
  then
    TITLE="Mobile"
  else
    TITLE=$(grep createCardHeader /www/cards/$CARD | sed -e 's/\(.*createCardHeader[^"]*"\)\([^"]*\)\(".*\)/\2/')
  fi
  if [ "$HIDDEN" != "0" -a "$HIDDEN" != "1" ]
  then
    HIDDEN=0
  fi
  SEQ=${CARD%%_*}
  if [ -z "$CARDS" ]
  then
    CARDS="$HIDDEN|$SEQ|$HIDDEN|$CARD|$MODAL|$TITLE|"
  else
    CARDS="$CARDS$IFS$HIDDEN|$SEQ|$HIDDEN|$CARD|$MODAL|$TITLE|"
  fi
done
[ $QUIET = n ] && echo

if [ -z "$CARDS" ]
then
  echo "ERROR: No card configurations found!"
  echo "Have you run tch-gui-unhide yet? You must execute tch-gui-unhide BEFORE configuring card sequence and visibility."
  exit
fi

apply_changes() {
    for CARD in $(echo "$CARDS" | tr ' ' ';' | sort)
    do
      HIDDEN=$(echo "$CARD" | cut -d'|' -f1)
      SEQ=$(echo "$CARD" | cut -d'|' -f2)
      FILE="/www/cards/$(echo "$CARD" | cut -d'|' -f4)"
      MODAL=$(echo "$CARD" | cut -d'|' -f5)
      NEW_FILE="/www/cards/${SEQ}_${FILE#*_}"
      RULE="card_$(basename ${FILE#*_} .lp)"
      if [ "$FILE" != "$NEW_FILE" ]
      then
        [ $QUIET = n ] && echo "Renaming $FILE to $NEW_FILE"
        mv "$FILE" "$NEW_FILE"
      fi
      uci set web.$RULE=card
      uci set web.$RULE.card="$(basename $NEW_FILE)"
      uci set web.$RULE.modal="$MODAL"
      uci set web.$RULE.hide="$HIDDEN"
    done
    [ $QUIET = n ] && echo "Applying updated configuration"
    uci commit web
    /etc/init.d/nginx restart
    [ $QUIET = n ] && echo "Done!!"
}

apply_defaults() {
  TMP=""
  for CARD in $(echo "$CARDS" | tr ' ' ';')
  do
    HIDDEN=$(echo "$CARD" | cut -d'|' -f3)
    FILE=$(echo "$CARD" | cut -d'|' -f4)
    MODAL=$(echo "$CARD" | cut -d'|' -f5)
    TITLE=$(echo "$CARD" | cut -d'|' -f6 | tr ';' ' ')
    HIDE=$HIDDEN
    case "${FILE#*_}" in
      broadband.lp) SEQ="002";;
      contentsharing.lp) SEQ="012";;
      cwmpconf.lp) SEQ="090";;
      Devices.lp) SEQ="006";;
      diagnostics.lp) SEQ="009";;
      eco.lp) SEQ="020";;
      firewall.lp) SEQ="008";;
      fon.lp) SEQ="010";;
      gateway.lp) SEQ="001";;
      internet.lp) SEQ="003";;
      iproutes.lp) SEQ="015";;
      LAN.lp) SEQ="005";;
      lte.lp) if [ "$(uci -q get version.@version[0].marketing_version)" = '17.2' ]; then SEQ="010"; else SEQ="003"; fi;;
      natalghelper.lp) SEQ="092";;
      parental.lp) SEQ="013";;
      printersharing.lp) SEQ="012";;
      qos.lp) SEQ="008";;
      relaysetup.lp) SEQ="018";;
      system.lp) SEQ="091";;
      telephony.lp) SEQ="008";;
      tod.lp) SEQ="015";;
      usermgr.lp) SEQ="011";;
      wanservices.lp) SEQ="007";;
      wireless_boosters.lp) SEQ="004";;
      wireless.lp) SEQ="004";;
      xdsl.lp) SEQ="093";;
      *) SEQ=$(basename $FILE | cut -c1-3);;
    esac
    if [ -z "$TMP" ]
    then
      TMP="0|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
    else
      TMP="$TMP${IFS}0|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
    fi
  done
  CARDS="$TMP"
  unset TMP
}

apply_minimal() {
  TMP=""
  for CARD in $(echo "$CARDS" | tr ' ' ';')
  do
    HIDDEN=$(echo "$CARD" | cut -d'|' -f3)
    FILE=$(echo "$CARD" | cut -d'|' -f4)
    MODAL=$(echo "$CARD" | cut -d'|' -f5)
    TITLE=$(echo "$CARD" | cut -d'|' -f6 | tr ';' ' ')
    HIDE=$HIDDEN
    case "${FILE#*_}" in
      contentsharing.lp) [ "$(uci -q get dlnad.config.enabled)" != "1" -a "$(uci -q get samba.samba.filesharing)" != "1" ] && HIDE=1;;
      cwmpconf.lp) [ ! -f /etc/init.d/cwmpd ] && HIDE=1;;
      natalghelper.lp) HIDE=1;;
      parental.lp) HIDE=1;;
      printersharing.lp) [ "$(uci -q get printersharing.config.enabled)" != "1" ] && HIDE=1;;
      qos.lp) HIDE=1;;
      relaysetup.lp) HIDE=1;;
      telephony.lp) [ "$(uci -q get mmpbx.global.enabled)" != "1" ] && HIDE=1;;
      tod.lp) HIDE=1;;
      system.lp) HIDE=1;;
      wanservices.lp) [ "$(uci -q get firewall.dmzredirects.enabled)" != "1" -a "$(uci -q get ddns.myddns_ipv4.enabled)" != "1" -a "$(uci -q get ddns.myddns_ipv6.enabled)" != "1" -a "$(uci -q get upnpd.config.enable_natpmp)" != "1" -a "$(uci -q get upnpd.config.enable_upnp)" != "1" ] && HIDE=1;;
      wireless_boosters.lp) [ "$(uci -q get multiap.agent.enabled)" != "1" -a "$(uci -q get multiap.controller.enabled)" != "1" ] && HIDE=1;;
      *) SEQ=$(basename $FILE | cut -c1-3);;
    esac
    if [ -z "$TMP" ]
    then
      TMP="$HIDE|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
    else
      TMP="$TMP$IFS$HIDE|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
    fi
  done
  CARDS="$TMP"
  unset TMP
}

apply_suggested() {
  TMP=""
  for CARD in $(echo "$CARDS" | tr ' ' ';')
  do
    HIDDEN=$(echo "$CARD" | cut -d'|' -f3)
    FILE=$(echo "$CARD" | cut -d'|' -f4)
    MODAL=$(echo "$CARD" | cut -d'|' -f5)
    TITLE=$(echo "$CARD" | cut -d'|' -f6 | tr ';' ' ')
    HIDE=$HIDDEN
    case "${FILE#*_}" in
      broadband.lp) SEQ="002";;
      contentsharing.lp) SEQ="019";;
      cwmpconf.lp) SEQ="026"; if [ ! -f /etc/init.d/cwmpd ]; then HIDE=1; fi;;
      Devices.lp) SEQ="009";;
      diagnostics.lp) SEQ="023";;
      eco.lp) SEQ="017";;
      firewall.lp) SEQ="010";;
      fon.lp) SEQ="005";;
      gateway.lp) SEQ="001";;
      internet.lp) SEQ="003";;
      iproutes.lp) SEQ="014";;
      LAN.lp) SEQ="009";;
      lte.lp) SEQ="004";;
      natalghelper.lp) SEQ="011"; HIDE="$HIDE_EXTRA";;
      nfc.lp) SEQ="004";;
      parental.lp) SEQ="021";;
      printersharing.lp) SEQ="020"; HIDE="$HIDE_EXTRA";;
      qos.lp) SEQ="016";;
      relaysetup.lp) SEQ="025"; HIDE="$HIDE_EXTRA";;
      system.lp) SEQ="012";;
      telephony.lp) SEQ="015";;
      tod.lp) SEQ="022";;
      usermgr.lp) SEQ="018";;
      wanservices.lp) SEQ="013";;
      wireless_boosters.lp) SEQ="007";;
      wireless.lp) SEQ="006";;
      xdsl.lp) SEQ="024";;
      *) SEQ=$(basename $FILE | cut -c1-3);;
    esac
    if [ -z "$TMP" ]
    then
      TMP="$HIDE|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
    else
      TMP="$TMP$IFS$HIDE|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
    fi
  done
  CARDS="$TMP"
  unset TMP
}

undo_changes() {
  TMP=""
  for CARD in $(echo "$CARDS" | tr ' ' ';')
  do
    HIDDEN=$(echo "$CARD" | cut -d'|' -f3)
    FILE=$(echo "$CARD" | cut -d'|' -f4)
    MODAL=$(echo "$CARD" | cut -d'|' -f5)
    TITLE=$(echo "$CARD" | cut -d'|' -f6 | tr ';' ' ')
    SEQ=$(basename $FILE | cut -c1-3)
    if [ -z "$TMP" ]
    then
      TMP="$HIDDEN|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
    else
      TMP="$TMP$IFS$HIDDEN|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
    fi
  done
  CARDS="$TMP"
  unset TMP
}

if [ "action$1" = "action-s" ]
then
  apply_suggested
  apply_changes
  exit
elif [ "action$1" = "action-d" ]
then
  apply_defaults
  apply_changes
  exit
elif [ "action$1" = "action-M" ]
then
  apply_suggested
  apply_minimal
  apply_changes
  exit
fi

MESSAGE=""
while [ true ]
do
  clear
  echo "tch-gui-unhide-cards"
  echo
  echo "$MESSAGE"
  echo
  MESSAGE=""
  I=0
  for CARD in $(echo "$CARDS" | tr ' ' ';' | sort)
  do
    I=$(( $I + 1 ))
    HIDDEN=$(echo "$CARD" | cut -d'|' -f1)
    TITLE=$(echo "$CARD" | cut -d'|' -f6 | tr ';' ' ')
    if [ $HIDDEN = "1" ]
    then
      TITLE="($TITLE)"
    fi
    printf "%2d %-18s" $I "$TITLE"
    if [ $(( $I % 4 )) -eq 0 ]
    then
      echo
    fi
  done
  if [ $(( $I % 4 )) -ne 0 ]
  then
    echo
  fi
  if [ $VERBOSE = y ]
  then
    echo
    I=0
    for CARD in $(echo "$CARDS" | tr ' ' ';' | sort)
    do
      I=$(( $I + 1 ))
      printf "%2d " $I
      echo $CARD | tr ';' ' ' | tr '|' '\t'
    done
  fi
  echo
  echo "NOTE: Titles in () indicate hidden cards. They will always appear above after the last visible card." 
  echo "NOTE: 'CWMP' card is only visible if CWMP has not been disabled"
  echo "NOTE: 'xDSL Config' card is only visible on DSL connections"
  echo
  echo "OPTIONS: A single card number between 1 and $I"
  echo "         d = order cards by the default sequence"
  echo "         m = hide all optional feature cards"
  echo "         s = order cards by a suggested sequence"
  echo "         u = undo changes"
  echo "         a = apply changes and quit"
  echo "         q = quit without applying changes"
  echo
  echo -n "Enter one of 1-$I/d/m/s/u/a/q: "
  read FROM
  echo
  case "$FROM" in
    a)  apply_changes
        break;;
    d)  apply_defaults;;
    m)  apply_minimal;;
    q)  break;;
    s)  apply_suggested;;
    u)  undo_changes;;
    *)  if [ "$FROM" -ge 1 -a "$FROM" -le "$I" ]
        then
          printf "For card #$FROM, enter h to hide, u to unhide, or new position number: "
          read TO
          if [ "$TO" = "h" -o "$TO" = "u" ]
          then
            if [ "$TO" = "h" ]
            then
              TO=1
            else
              TO=0
            fi
            TMP=""
            I=0
            for CARD in $(echo "$CARDS" | tr ' ' ';' | sort)
            do
              I=$(( $I + 1 ))
              SEQ=$(echo "$CARD" | cut -d'|' -f2)
              HIDDEN=$(echo "$CARD" | cut -d'|' -f3)
              FILE=$(echo "$CARD" | cut -d'|' -f4)
              MODAL=$(echo "$CARD" | cut -d'|' -f5)
              TITLE=$(echo "$CARD" | cut -d'|' -f6 | tr ';' ' ')
              if [ $I -eq $FROM ]
              then
                HIDE=$TO
              else
                HIDE=$(echo "$CARD" | cut -d'|' -f1)
              fi
              if [ -z "$TMP" ]
              then
                TMP="$HIDE|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
              else
                TMP="$TMP$IFS$HIDE|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
              fi
            done
            CARDS="$TMP"
            unset TMP
          elif [ "$TO" -ge 1 -a "$TO" -le "$I" -a "$TO" -ne "$FROM" ]
          then
            TMP=""
            I=0
            for CARD in $(echo "$CARDS" | tr ' ' ';' | sort)
            do
              I=$(( $I + 1 ))
              HIDDEN=$(echo "$CARD" | cut -d'|' -f3)
              FILE=$(echo "$CARD" | cut -d'|' -f4)
              MODAL=$(echo "$CARD" | cut -d'|' -f5)
              TITLE=$(echo "$CARD" | cut -d'|' -f6 | tr ';' ' ')
              HIDE=$(echo "$CARD" | cut -d'|' -f1)
              if [ $I -eq $FROM ]
              then
                SEQ=$(printf "%03d" $(( $TO )))
              elif [ $FROM -lt $TO -a $I -gt $FROM -a $I -le $TO ]
              then
                SEQ=$(printf "%03d" $(( $I - 1 )))
              elif [ $FROM -gt $TO -a $I -ge $TO -a $I -lt $FROM ]
              then
                SEQ=$(printf "%03d" $(( $I + 1 )))
              else
                SEQ=$(printf "%03d" $I)
              fi
              if [ -z "$TMP" ]
              then
                TMP="$HIDE|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
              else
                TMP="$TMP$IFS$HIDE|$SEQ|$HIDDEN|$FILE|$MODAL|$TITLE|"
              fi
            done
            CARDS="$TMP"
            unset TMP
          else
            MESSAGE="ERROR: Options are 'h' to hide a card, 'v' to make a card visible, or a number between 1 and $I!"
          fi
        else
          MESSAGE="ERROR: Please select a card number between 1 and $I (but not $FROM)!"
        fi;;
  esac
done
