#!/bin/sh /etc/rc.common
# Based on https://github.com/skyformat99/eqos/blob/master/files/eqos.init

START=70

parse_device() {
  local cfg="$1" enabled mac download upload

  config_get_bool enabled "$cfg" enabled 0
  [ $enabled -eq 0 ] && return 0

  config_get mac "$cfg" mac
  config_get download "$cfg" download
  config_get upload "$cfg" upload

  /usr/sbin/bqos add $mac $download $upload
}

bqos_start() {
  local cfg="$1" enabled download upload r2q

  config_get_bool enabled "$cfg" enabled 0
  [ $enabled -eq 0 ] && return 0

  config_get download "$cfg" download 50
  config_get upload "$cfg" upload 20
  config_get r2q "$cfg" r2q 35

  /usr/sbin/bqos start $download $upload $r2q

  config_foreach parse_device device
}

start() {
  /usr/sbin/bqos stop

  config_load bqos
  config_foreach bqos_start bqos
}

stop() {
  /usr/sbin/bqos stop
}