#!/bin/sh

usage() {
cat <<EOH
Enables or disables reboot on core dump.
If you have a process that is continually crashing and core dumping,
use this script to disable reboot on coredump.

Usage: $0 -on|-off

Parameters:
 -on    Enables reboot on core dump.
 -off   Disables reboot on core dump.

EOH
exit
}

ENABLED="$(uci -q get system.@coredump[0].reboot)"
while getopts :onff option
do
  case "${option}" in
    o) SETTING="";;
    n) SETTING=on;;
    f) SETTING=off;;
    ?) usage;;
  esac
done
if [ -z "$SETTING" ]
then
  if [ "$ENABLED" = "0" ]
  then
    echo "Reboot on core dump currently DISABLED - re-run script with -on option to enable"
else
    echo "Reboot on core dump currently ENABLED - re-run script with -off option to disable"
fi
else
  case "$SETTING" in
    on)
        if [ "$ENABLED" = "0" ]
        then
          uci set system.@coredump[0].reboot='1'
          uci commit system
        else
          echo Already enabled!!
        fi;;
    off)
        if [ "$ENABLED" = "1" ]
        then
          uci set system.@coredump[0].reboot='0'
          uci commit system
        else
          echo Already disabled!!
        fi;;
  esac
fi
