#!/bin/sh

if [ -z "$1" ]; then
  echo "ERROR: No password specified"
  echo
fi
if [ -z "$1" -o "o$1" = "o-?" ]; then
cat <<EOH
Allows you to set or reset the web admin password.

Usage: $0 newpassword

Parameters:
 newpassword   the new admin password for the GUI. (Required)

EOH
exit
fi

USR="admin"
KEY="$1"
SRP=$(newsrpuser -f -u $USR -p $KEY)
SALT=$(echo $SRP | cut -d' ' -f1)
VERIFIER=$(echo $SRP | cut -d' ' -f2)

uci set web.usr_admin.srp_salt=$SALT
uci set web.usr_admin.srp_verifier=$VERIFIER
uci commit web

/etc/init.d/nginx restart

echo Web GUI password for admin set to: $KEY
