#!/bin/sh

SCRIPT="$(basename $0)"

if [ "o$1" = "o-?" ]; then
cat <<EOH
Sets the optimal bank plan.

Effectively the same as the procedure described in
https://hack-technicolor.rtfd.io/en/stable/Hacking/PostRoot/#bank-planning.

Usage: $0

EOH
exit
fi

echo -n "Enter y to attempt to set the optimal bank plan, or anything else to exit now: "
read
if [ "$REPLY" = "y" -o "$REPLY" = "Y" ]
then
  echo Ensure two banks match in sizes
  BANK_COUNT=$(grep -c bank_ /proc/mtd)
  if [ $BANK_COUNT = 2 ] && [ "$(grep bank_1 /proc/mtd | cut -d' ' -f2)" =  "$(grep bank_2 /proc/mtd | cut -d' ' -f2)" ]
  then
    BANK1_SIZE="$(grep bank_1 /proc/mtd | cut -d' ' -f2)"
    BANK2_SIZE="$(grep bank_2 /proc/mtd | cut -d' ' -f2)"
    if [ "$BANK1_SIZE" = "$BANK2_SIZE" ]
    then
      if [ "$(cat /proc/banktable/booted)" = "bank_1" ]; then
        echo Copy firmware into bank_2...
        mtd -e bank_2 write /dev/$(grep bank_1 /proc/mtd | cut -d: -f1) bank_2
      else
        echo Already booted from bank_2 - Firmware copy not required
      fi
      echo Make a temp copy of the overlay for the booted firmware
      cp -rf /overlay/$(cat /proc/banktable/booted) /tmp/bank_overlay_backup
      echo Clean up jffs2 space by removing existing old overlays
      rm -rf /overlay/*
      echo Use the previously made temp copy as overlay for bank_2
      cp -rf /tmp/bank_overlay_backup /overlay/bank_2
      echo Activate bank_1
      echo bank_1 > /proc/banktable/active
      echo Make sure above changes get written to flash
      sync
      echo Erase firmware in bank_1
      mtd erase bank_1
      echo "################################################"
      echo "# Operation Complete.                          #"
      echo "#                                              #"
      echo "# About to emulate system crash to hard reboot #"
      echo "# for the new bank plan to take effect!        #"
      echo "################################################"
      echo c > /proc/sysrq-trigger;
    else
      echo
      echo "Operation ABORTED!!"
      echo
      echo "ERROR: Bank 1 and Bank 2 are different sizes??"
      echo " - Bank 1 = $BANK1_SIZE"
      echo " - Bank 2 = $BANK2_SIZE"
    fi
  else
    echo
    echo "Operation ABORTED!!"
    echo
    echo "ERROR: Unexpected bank count - Expected 2 but found $BANK_COUNT"
  fi
fi
