#!/bin/sh

SCRIPT="$(basename $0)"

usage() {
cat <<EOH
Downloads and installs the latest version of the System CA Certificates.

Usage: $0 [options]

Options:
 -v  Verbose mode
 -C  Adds or removes the scheduled monthly cron job
 -U  Download the latest version of $SCRIPT from GitHub

EOH
exit
}

upgrade() {
  RESPONSE_CODE=$(curl -kLsI -o /dev/null -w '%{http_code}' https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT)
  if [ "$RESPONSE_CODE" = 200 ]
  then
    curl -kL -o $SCRIPT https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/$SCRIPT
    if [ $? -eq 0 ]
    then
      chmod +x $SCRIPT
      echo "[$SCRIPT] Successfully downloaded $SCRIPT."
    else
      echo "[$SCRIPT] Failed to download $SCRIPT."
    fi
  elif [ "$RESPONSE_CODE" = 404 ]
  then
    echo "[$SCRIPT] ERROR! Not found on GitHub???"
  elif [ "$RESPONSE_CODE" = 000 ]
  then
    echo "ERROR! No Internet connection???"
  else
    echo "[$SCRIPT] ERROR! Unknown response code $RESPONSE_CODE"
  fi
  exit
}

CRON=N
CURL_OPT="-s"
LGGR_OPT=""

while getopts :vCU option
do
 case "${option}" in
  v)  CURL_OPT=""; LGGR_OPT="-s";;
  C)  CRON=Y;;
  U)  upgrade;;
  *)  usage;;
 esac
done
shift $((OPTIND-1))

if [ $CRON = Y ]; then
  grep -q "$SCRIPT" /etc/crontabs/root
  if [ $? = 0 ]
  then
    sed -e "/$SCRIPT/d" -i /etc/crontabs/root
    echo Scheduled update has been removed.
  else
    mm=$(awk 'BEGIN{srand();print int(rand()*59);}')
    hh=$(awk 'BEGIN{srand();print int(rand()*3)+2;}')
    dd=$(awk 'BEGIN{srand();print int(rand()*28);}')
    echo "$mm $hh $dd * * $(cd $(dirname $0); pwd)/$SCRIPT" >> /etc/crontabs/root
    echo System certificates update has been scheduled to execute at $hh:$(printf '%02d' $mm)am on day $dd of each month.
    echo Execution messages will be written to the system log, and can be viewed with the following command:
    echo
    echo "  logread -e rpc.gui.opkg"
    echo
  fi
  /etc/init.d/cron reload
  exit
fi

SRC="https://downloads.openwrt.org/releases/packages-21.02/arm_cortex-a9/base/"
for IPK in $(curl -sk $SRC/Packages.gz | gunzip | grep '^Filename: ca-' | cut -d' ' -f2)
do
  curl $CURL_OPT -kL $SRC/$IPK -o /tmp/$IPK && opkg --force-overwrite install /tmp/$IPK 2>&1 | logger $LGGR_OPT -t rpc.gui.opkg -p user.info && rm /tmp/$IPK
done

curl $CURL_OPT -kLz /etc/ssl/certs/ca-certificates.crt -o /etc/ssl/certs/ca-certificates.crt https://curl.se/ca/cacert.pem | logger $LGGR_OPT -t rpc.gui.opkg -p user.info

if [ -z "$ENV" ]; then
  grep -q SSL_CERT_FILE /etc/profile || echo "export SSL_CERT_FILE='/etc/ssl/cert.pem'" >> /etc/profile
else
  grep -q SSL_CERT_FILE $ENV || echo "SSL_CERT_FILE='/etc/ssl/cert.pem'" >> $ENV
fi

