#!/bin/sh
. /lib/functions.sh

config_load network
config_get proto "$INTERFACE" "proto" "unknown"
config_get listen_port "$INTERFACE" "listen_port"

[ "$proto" = "wireguard" -a -n "$listen_port" ] && /usr/share/tch-gui-unhide/wireguard-peer-firewall.sh

exit 0
