#!/bin/sh

cd $(dirname $0)

if [ -e .extras ]; then
  rm .extras
fi
for d in $(find . -maxdepth 1 -type d ! -path . -printf '%P\n' | sort | xargs); do
  source="$d/$d.sh"
  if [ -f "$source" ]; then
    target="../tch-gui-unhide-xtra.$d"
    if [ ! -f "$d/.skip" ]; then
      [ ! -f "$d/.manual" ] && echo "tch-gui-unhide-xtra.$d" >> .extras
      if [ "$1" = "$d" -o ":$1" = ":-all" -o ! -e $target -o $(find $d -newer $target -type f 2>/dev/null | wc -l) -gt 0 ]; then
        echo Creating $target...
        cp "$source" "$target"
        grep -n 'cat *<<' "$source" | grep -v '>>' | sed -e 's/:\|<\|>\|"\|cat//g' | sort -nr | while read -r line name file
        do
          if [ -e $d$file ]; then
            if [ -n "$(tail -c1 $d$file)" ]; then
              sed -e "${line}a\\\n" -i "$target"
            fi
            sed -e "${line}r $d$file" -i "$target"
          fi
        done
      fi
    else
      [ -f "$target" ] && rm "$target"
    fi
  fi
done

