#!/bin/sh /etc/rc.common
 
USE_PROCD=1
 
START=95
STOP=01

__INTERFACES=""

find_static_wan_iface() {
  local cfg="$1"
  if [ "$cfg" = "wan" -o "$cfg" = "wan6" ]; then
    local enabled proto ifname gateway

    config_get proto "$cfg" proto
    config_get ifname "$cfg" ifname
    config_get gateway "$cfg" gateway
    
    if [ "$proto" = "static" -a -n "$ifname" -a -n "$gateway" ]; then
      __INTERFACES="$__INTERFACES $ifname,$gateway"
    fi
  fi
}

config_load network
config_foreach find_static_wan_iface interface

start_service() {
  if [ -n "$__INTERFACES" ]; then
    procd_open_instance
    procd_set_param command $(which lua) /usr/share/tch-gui-unhide/static-wan-routes-monitor.lua $__INTERFACES
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
  fi
}